name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Setup Chrome and Chromedriver
        uses: browser-actions/setup-chrome@v1
        with:
          chrome-version: 'latest'
          check-latest: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Clean project
        run: ./gradlew clean

      - name: Generate Allure report
        run: ./gradlew allureReport
        if: always()

      - name: Upload Allure report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: allure-report
          path: build/reports/allure-report/

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Generate and submit dependency graph
        uses: gradle/actions/dependency-submission@v4.0.0
